### ISSUE TITLE
SpringMvcPublisher is a singleton with mutable state

### ISSUE THREAD

**Issue by whiskeysierra** [bertilmuth/poem-springboot#1]
Follow up from: https://twitter.com/whiskeysierra84/status/1145039274888314880

> I know it's just an example but the SpringMvcPublisher is a singleton with mutable state. How would a production ready implementation look like? Your blog post is the only one I could find where someone tried to implement the pattern without simple return values.

> My gut feeling says: let’s create a different @Scope for the driver() method in the poem.springboot.Application class.
> In particular, each user needs her own ModelRunner instance, which is controlled by the boundary class.

Technically that might work, e.g. using `@RequestScope`, ignoring the indirect dependency on `ThreadLocal` and therefore thread context. Any thread switch in between might be tricky.

But moving back from this one more step. It's not so much a problem that needs to be solved for Spring but rather should be an issue for any driving adapter that needs a result synchronously as a return value. Is it actually a rule of hexagonal architecture to not have any return values in left-side ports?

**Comment by whiskeysierra** [comment]
https://twitter.com/whiskeysierra84/status/1145114987830153216

**Comment by bertilmuth** [comment]
Concerning the Spring specific solution: I added a Session @Scope, as this reflects most closely how I think about use cases in general (they are tied to a user session). I load tested the solution against 50 users, and it worked - in contrast to the original solution. Thanks for pointing it out.

Concerning your more general question: it really depends, as so often. In my hexagonal architecture example, I assumed that the driving technology (for providing data to the hexagon) may be different from the driven technology (for displaying data). For example: the user asks by the console, but the poem is written to a file or send via email.

If you make that assumption, then you run into problems if you use driver ports with methods that return values. Suddenly, the driver adapter somehow needs to access the driven side, and that's not good.

On the other hand, if you know that the technology on the driver and driven side are the same and stay the same, i.e. only change together, then it's fine and probably easier if you have a driver port with methods that return values. The reason I didn't go that way is: how is the hexagon supposed to know that? 

My solution is compatible with both cases, even though it is a bit more complicated when the driver/driven technology match, as in the Spring Boot example.

**Comment by whiskeysierra** [comment]
> Suddenly, the driver adapter somehow needs to access the driven side, and that's not good.

Agreed.

> On the other hand, if you know that the technology on the driver and driven side are the same and stay the same, i.e. only change together, then it's fine and probably easier if you have a driver port with methods that return values.

To me this boils down to the feeling that the technology of the driving adapter dictates the API style of the hexagon and that feels wrong to me.

> The reason I didn't go that way is: how is the hexagon supposed to know that?

Not only can't it know, since it doesn't know anything about its drivers at all, apart from the fact that they will use the driving port. 

> My solution is compatible with both cases, even though it is a bit more complicated when the driver/driven technology match, as in the Spring Boot example. And the only ways to "return" values in such a solution is by mutating state.

I was thinking about a slightly different approach. Let's say I want to design the ports of the hexagon (both sides) in such a way that the hexagon is agnostic to the communication paradigm than we need to have both: return values and driven ports. Since I don't want to maintain two separate yet very closely related things, what about changing the API (driving port) and SPI (driven port) to primary talk about events.

The driving port could return a `Future<Event>` (or something along those lines) and the driven port could be defined in terms of event listeners. That way I define both things as a single thing which is the concrete event model. They differ in how we get it to the right receiver, so the hexagon will always need to publish and return together.

**Comment by bertilmuth** [comment]
Very interesting. What you get in this case is very loose coupling. The hexagon doesn't even know the specific driven ports (which may have downsides as well, depending on the requirements). The requirementsascode library already has partial support for publishing to driven side, via the `submitPublish()` method, see [home page](https://github.com/bertilmuth/requirementsascode). Using a `Future` to return values is an interesting thought. When I find the time, I will create a variant of the sample application that showcases it.

**Comment by bertilmuth** [comment]
I have developed a solution for this problem, please have a look at it.
Here's the next generation of the core hexagonal sample application:
https://github.com/bertilmuth/poem-hexagon-nextgen
And here's the next generation of the Spring Boot application:
https://github.com/bertilmuth/poem-springboot-nextgen

**Comment by bertilmuth** [comment]
I updated the nextgen projects to 
a) avoid shared mutable state
b) provide an elegant solution that allows you to configure if you want to return events, or forward them to driven adapters. See also this [tweets](https://twitter.com/BertilMuth/status/1146691305877180417).

**Comment by whiskeysierra** [comment]
> a) avoid shared mutable state

What about this? If SpringMvcDriver is a singleton it's still mutable, shared state.

https://github.com/bertilmuth/poem-springboot-nextgen/blob/a371c584fe86bdedb2512dd0bca8315767216760/src/main/java/poem/springboot/driver_adapter/SpringMvcDriver.java#L11

There is no need for this actually. This would fix it:

```java
public Object reactTo(Object command) {
    final CompletableFuture<Object> future = new CompletableFuture<>();
    boundary.reactTo(command, future::complete);
    return future.join();
}
```

That's actually a pretty common pattern to change a callback-based API to return a promise/future.

Why don't you just introduce a return value that returns a future and can be ignored, if a driver doesn't care? Delegation to a driven port would happen then depending on configuration at construction time, not based on the callback at runtime.

```java
public Object reactTo(Object command) {
    return boundary.reactTo(command).join();
}
```

**Comment by bertilmuth** [comment]
Thank you for your comment! You're right, one mutable field slipped through. I used it for testing purposes, but I have adapted the test and provided the first solution as you described.
I have to think about your second proposal, the consequences and benefits.

**Comment by bertilmuth** [comment]
You wrote: "Delegation to a driven port would happen then depending on configuration at construction time". How? Do you think something like this in the driver port:
```
public Object reactTo(Object command) {
    Object event = boundary.reactTo(command).join();
    // Forward event to driven port...
}
```

**Comment by whiskeysierra** [comment]
Like this:

```java
class Hexagon implement Boundary {
    private final DrivenPort port;

    public Future<Event> reactTo(command) {
        // do stuff and create future
        future.thenAccept(port::publish);
        return future;
    }

}
```

The driven port is defined at construction time of the `Hexagon`.

**Comment by bertilmuth** [comment]
I have implemented the changes. Care to make a review?

**Comment by bertilmuth** [comment]
Resolved.
